version: '3'

services:
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - './mosquitto.conf:/mosquitto/config/mosquitto.conf:ro'
      - mqtt-data:/mosquitto/data
    ports: 
      - "32771:1883"

  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"

  telegraf:
    image: nuntz/telegraf-snmp
    volumes:
      - './telegraf.conf:/etc/telegraf/telegraf.conf:ro'
    depends_on:
      - mqtt
      - influxdb

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

volumes:
  mqtt-data:
    driver: local
